name: Build Linux Wheels (per arch)

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner label to use for the build job'
        type: string
        required: true
      with-cuda:
        description: 'Enable CUDA wheel builds'
        type: string
        default: disable
      with-rocm:
        description: 'Enable ROCm wheel builds'
        type: string
        default: disable
      trigger-event:
        description: 'The GitHub event name that triggered the parent workflow'
        type: string
        required: true

jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: wheel
      os: linux
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      with-cuda: ${{ inputs.with-cuda }}
      with-rocm: ${{ inputs.with-rocm }}
      with-cpu: disable

  build:
    needs: generate-matrix
    uses: pytorch/test-infra/.github/workflows/build_wheels_linux.yml@main
    with:
      repository: meta-pytorch/torchcomms
      ref: ""
      pre-script: ""
      post-script: ""
      build-platform: "python-build-package"
      build-command: "scripts/_build_wheel.sh"
      smoke-test-script: "scripts/smoke_test.py"
      package-name: torchcomms
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      trigger-event: ${{ inputs.trigger-event }}
      runner: ${{ inputs.runner }}
