name: Build Linux Wheels

on:
  pull_request:
  push:
    branches:
      - main
      - nightly
      - release/*
    tags:
        # NOTE: Binary build pipelines should only get triggered on release candidate builds
        # Release candidate tags look like: v1.11.0-rc1
        - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:

jobs:
  build-cuda:
    uses: ./.github/workflows/build-wheels-arch.yml
    with:
      runner: linux.g5.12xlarge.nvidia.gpu
      with-cuda: enable
      trigger-event: ${{ github.event_name }}

  build-rocm:
    uses: ./.github/workflows/build-wheels-arch.yml
    with:
      runner: linux.4xlarge
      with-rocm: enable
      trigger-event: ${{ github.event_name }}
